# Source: jxboot-helmfile-resources/templates/environments.yaml
apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "production"
    team: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: "production"
  namespace: jx
spec:
  source:
    ref: "master"
    url: https://github.com/twygmbh/kubernetes-production.git
  kind: Permanent
  label: Production
  order: 500
  promotionStrategy: "Manual"
  namespace: "jx-production"
  remoteCluster: true
