# Source: node-demo-app/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-07T23:21:36Z"
  deletionTimestamp: null
  name: 'node-demo-app-0.0.1'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.1
      sha: 718427ce2b82e26a5f760f6ced7bcc509cafa410
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 08344f63dbe358a7337834a93f4f1f39c5a1744c
    - author:
        email: reto@twy.gmbh
        name: Reto Ryter
      branch: master
      committer:
        email: reto@twy.gmbh
        name: Reto Ryter
      message: |
        chore: Jenkins X build pack
      sha: 2b970ea311f29aa8a9c2837e7e76bfbee9d813c2
  gitHttpUrl: https://github.com/twygmbh/node-demo-app
  gitOwner: twygmbh
  gitRepository: node-demo-app
  name: 'node-demo-app'
  releaseNotesURL: https://github.com/twygmbh/node-demo-app/releases/tag/v0.0.1
  version: v0.0.1
status: {}
