filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
repositories:
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: dev
  url: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
releases:
- chart: jx3/jx-verify
  name: jx-verify
  namespace: jx-staging
  values:
  - jx-values.yaml
- chart: dev/node-demo-app
  version: 0.0.1
  name: node-demo-app
  namespace: jx-staging
templates: {}
renderedvalues: {}
