# Source: jx-verify/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: jx-verify-gc-jobs
  annotations:
    kapp.k14s.io/disable-wait: ""
  labels:
    app: jx-verify-gc-jobs
    release: jx-verify
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx-production
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - jx-verify
            - pods
          env:
            - name: XDG_CONFIG_HOME
              value: /home
          image: gcr.io/jenkinsxio/jx-verify:0.0.70
          imagePullPolicy: IfNotPresent
          name: job
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: jx-verify-gc-jobs
