apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        twygmbh/kubernetes-production: true
        twygmbh/kubernetes-staging: true
        twygmbh/node-demo-app: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        twygmbh/kubernetes-production: merge
        twygmbh/kubernetes-staging: merge
        twygmbh/node-demo-app: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - twygmbh/kubernetes-staging
        - twygmbh/kubernetes-production
        - twygmbh/node-demo-app
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - twygmbh/kubernetes-staging
        - twygmbh/kubernetes-production
        - twygmbh/node-demo-app
      target_url: http://dashboard.staging.twy.gmbh
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
