apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - twygmbh/kubernetes-staging
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - twygmbh/kubernetes-production
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - twygmbh/k8s-node-example-app
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - twygmbh/kubernetes-production
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      twygmbh/k8s-node-example-app:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      twygmbh/kubernetes-production:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      twygmbh/kubernetes-staging:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - twygmbh/kubernetes-staging
      trusted_org: todo
    - repos:
      - twygmbh/kubernetes-production
      trusted_org: todo
    - repos:
      - twygmbh/k8s-node-example-app
      trusted_org: todo
    - repos:
      - twygmbh/kubernetes-production
      trusted_org: todo
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
